### PR TITLE
Update OSF dependent repos to latest stable points

### PR DESCRIPTION
**Pull request by ed-sharma**
There are total of 4 change requests in this pull request:

96f2fa5 Update microcode binaries for deltalake
9d3e79b Update coreboot and deps to latest stable repo picks
5916bd2 Updated u-root to latest stable release from github
eae69ef  Update FSP to latest stable hash (CedarIsland FSP 2.2.0.33)

I have tested linuxboot on DeltaLake with these changes and it works.

### CODE REVIEW

**Review by jonzhang-fb — COMMENTED** [review]
16.6 to 17.1 (instead of 17.7)

**Comment by jonzhang-fb** [comment]
How did you do the test? As developer's sanity test, I would recommend to boot to OS, and compare following with the image without this patchset:
1) boot log. no regression.
2) dmesg. no regression.
3) lscpu/ifconfig/"cat /proc/meminfo"/"lspci -tv". no unreasonable change.
4) 5 times of warm reboots. no issue.

**Comment by ed-sharma** [comment]
> How did you do the test? As developer's sanity test, I would recommend to boot to OS, and compare following with the image without this patchset:
> 
>     1. boot log. no regression.
> 
>     2. dmesg. no regression.
> 
>     3. lscpu/ifconfig/"cat /proc/meminfo"/"lspci -tv". no unreasonable change.
> 
>     4. 5 times of warm reboots. no issue.

The review comments are incorporated and suggested testing performed with no noticed regression. Please review and approve.

**Comment by jonzhang-fb** [comment]
There are 14 commits now, some of them should be squashed as appropriate. In the end, only 4 commits are expected.

**Comment by jonzhang-fb** [comment]
For the subject of all 4 commits, please prefix them with "Wiwynn/DeltaLake: "

**Comment by ed-sharma** [comment]
Commits are updated with recommended change

**Comment by johnnylinwiwynn** [comment]
Verified it can build and boot up OS.

**Pull request merged**
