### PR TITLE
Add LinuxBoot README.

### PR DESCRIPTION
**Pull request by hugelgupf**
cc @rminnich
cc @zaolin
cc @vejmarie 
cc @dhendrix

### CODE REVIEW

**Comment by vejmarie** [comment]
We probably could add a "supported OCP hardware list" I liked Tram array with the various "working" feature from our latest hackathon ?

**Comment by hugelgupf** [comment]
I messed up the table, please don't merge yet :)

**Comment by hugelgupf** [comment]
Fixed it.

**Comment by hugelgupf** [comment]
See preview at https://github.com/hugelgupf/OSF/blob/42006c1765880dfb91bedc2374eb9797af11909d/LinuxBoot/README.md

**Comment by hugelgupf** [comment]
ping @rajeevsharma1?

**Pull request merged**
